# See: https://github.com/denoland/setup-deno
name: Render Loop CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Lint Sources
        run: |
          deno fmt --check
          deno lint
      - name: Run Tests
        run: deno task test

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.    

    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish
